### ISSUE TITLE
UndefVarError: `TotalEdgeWeightsPerNode` not defined

### ISSUE THREAD

**Issue by KarlKaise** [kaji331/ASCT#1]
While running the pbmck3 notebook I encountered following issue when executing this code 

PCA!(obj)
RunUMAP!(obj)
RunTSNE!(obj)
Clustering!(obj)

Issue::

UndefVarError: `TotalEdgeWeightsPerNode` not defined

Stacktrace:
 [1] AutomaticSingleCellToolbox.NetWork(nodes_number::Int64, node_weights::Vector{Float32}, first_neighbor_ind::Vector{Int64}, neighbor::Vector{Int64}, edge_weights::Vector{Float32})
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Louvain.jl:45
 [2] AutomaticSingleCellToolbox.NetWork(nodes_number::Int64, node_weights::Vector{Float32}, first_neighbor_ind::Vector{Int64}, neighbor::Vector{Int64}, edge_weights::Vector{Float32})
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Louvain.jl:54 [inlined]
 [3] MatrixToNetwork(node1::Vector{Int64}, node2::Vector{Int64}, edge_weights::Vector{Float32}, fun::Int64, nodes_number::Int64)
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Louvain.jl:389
 [4] ModClustering(nn::SparseArrays.SparseMatrixCSC{Float64, Int64}; modularity_fun::Int64, resolution::Float64, algorithm::Int64, rsn::Int64, itn::Int64, seed::Int64)
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/ModularityClustering.jl:18
 [5] ModularityClustering!(obj::AutomaticSingleCellToolbox.WsObj; modularity_fun::Int64, algorithm::Int64, reduction::String, num_pc::Int64, network::String, K::Int64, resolution::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, prune::Float64, random_starts_number::Int64, iter_number::Int64, seed::Int64)
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Clustering.jl:282
 [6] Clustering!(obj::AutomaticSingleCellToolbox.WsObj; method::String, reduction::Symbol, use_pc::String, tree_K::Int64, resolution::Symbol, cluster_K::Nothing, cluster_K_max::Int64, dist::String, network::String, random_starts_number::Int64, iter_number::Int64, prune::Float64, seed::Int64)
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Clustering.jl:51
 [7] Clustering!(obj::AutomaticSingleCellToolbox.WsObj)
   @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Clustering.jl:3
 [8] top-level scope
   @ In[9]:4
   
I would be grateful for any advice how to resolve this. Thank you

**Comment by kaji331** [comment]
> While running the pbmck3 notebook I encountered following issue when executing this code
> 
> PCA!(obj) RunUMAP!(obj) RunTSNE!(obj) Clustering!(obj)
> 
> Issue::
> 
> UndefVarError: `TotalEdgeWeightsPerNode` not defined
> 
> Stacktrace: [1] AutomaticSingleCellToolbox.NetWork(nodes_number::Int64, node_weights::Vector{Float32}, first_neighbor_ind::Vector{Int64}, neighbor::Vector{Int64}, edge_weights::Vector{Float32}) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Louvain.jl:45 [2] AutomaticSingleCellToolbox.NetWork(nodes_number::Int64, node_weights::Vector{Float32}, first_neighbor_ind::Vector{Int64}, neighbor::Vector{Int64}, edge_weights::Vector{Float32}) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Louvain.jl:54 [inlined] [3] MatrixToNetwork(node1::Vector{Int64}, node2::Vector{Int64}, edge_weights::Vector{Float32}, fun::Int64, nodes_number::Int64) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Louvain.jl:389 [4] ModClustering(nn::SparseArrays.SparseMatrixCSC{Float64, Int64}; modularity_fun::Int64, resolution::Float64, algorithm::Int64, rsn::Int64, itn::Int64, seed::Int64) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/ModularityClustering.jl:18 [5] ModularityClustering!(obj::AutomaticSingleCellToolbox.WsObj; modularity_fun::Int64, algorithm::Int64, reduction::String, num_pc::Int64, network::String, K::Int64, resolution::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, prune::Float64, random_starts_number::Int64, iter_number::Int64, seed::Int64) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Clustering.jl:282 [6] Clustering!(obj::AutomaticSingleCellToolbox.WsObj; method::String, reduction::Symbol, use_pc::String, tree_K::Int64, resolution::Symbol, cluster_K::Nothing, cluster_K_max::Int64, dist::String, network::String, random_starts_number::Int64, iter_number::Int64, prune::Float64, seed::Int64) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Clustering.jl:51 [7] Clustering!(obj::AutomaticSingleCellToolbox.WsObj) @ AutomaticSingleCellToolbox ~/.julia/packages/AutomaticSingleCellToolbox/XD9LB/src/Clustering.jl:3 [8] top-level scope @ In[9]:4
> 
> I would be grateful for any advice how to resolve this. Thank you

I forgot some inner functions by code organization. Please try again!

**Comment by KarlKaise** [comment]
Perfect, thank you. Run pkg> update command in Julia pkg command and it worked!

**Comment by KarlKaise** [comment]
Other, question. Can I ask how precisely was the integrated object - "harmony_stim.jld2, in the harmony notebook produced? Was it transformed from the Seurat object? If so, which metadata were used. Thank you a lot in advance for help.

**Comment by kaji331** [comment]
> Other, question. Can I ask how precisely was the integrated object - "harmony_stim.jld2, in the harmony notebook produced? Was it transformed from the Seurat object? If so, which metadata were used. Thank you a lot in advance for help.

Hi, I shared this file in the [box.com](https://app.box.com/s/4bzihajayebqkyrqnd21vw85qipj19af). I will update the jupyter file asap.

**Comment by KarlKaise** [comment]
Thank you very much :)
