### ISSUE TITLE
`Clustering!` takes forever with multithreading.

### ISSUE THREAD

**Issue by mdhe1248** [kaji331/ASCT#2]
First, Thank you for developing such a nice tool with Julia. I believe, my issue is not critical but wanted to report. I played with your pbmc3k notebook example and noticed that if I set multithreading, `clustering!` does not function well. 
In my bashrc, I have the line below:
```
export JULIA_NUM_THREADS=12 
```
If I comment out the line, then the notebook works well.

**Comment by kaji331** [comment]
Thank you for your help! I will fix it asap.

获取Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
发件人: donghoon ***@***.***>
发送时间: 星期四, 九月 5, 2024 5:44:21 上午
收件人: kaji331/ASCT ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kaji331/ASCT] `Clustering!` takes forever with multithreading. (Issue #2)


First, Thank you for developing such a nice tool with Julia. I believe, my issue is not critical but wanted to report. I played with your pbmc3k notebook example and noticed that if I set multithreading, clustering! does not function well.
In my bashrc, I have the line below:

export JULIA_NUM_THREADS=12


If I comment out the line, then the notebook works well.

―

**Comment by kaji331** [comment]
> First, Thank you for developing such a nice tool with Julia. I believe, my issue is not critical but wanted to report. I played with your pbmc3k notebook example and noticed that if I set multithreading, `clustering!` does not function well. In my bashrc, I have the line below:
> 
> ```
> export JULIA_NUM_THREADS=12 
> ```
> 
> If I comment out the line, then the notebook works well.

New version 0.9.2 fix this error.
